[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    '@juicebox=lib/juice-contracts-v2',
    '@chainlink=lib/chainlink/',
    '@openzeppelin=lib/openzeppelin-contracts',
    '@paulrberg/contracts/math/=lib/prb-math/contracts',
    'prb-math=lib/prb-math/',
    'forge-std/=lib/forge-std/src/',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config